#ifndef sat_widgets_included
#define sat_widgets_included
//----------------------------------------------------------------------

#include "sat.h"
#include "gui/sat_widget.h"

//

#include "gui/widgets/sat_button_widget.h"
#include "gui/widgets/sat_button_row_widget.h"
#include "gui/widgets/sat_circular_waveform_widget.h"
#include "gui/widgets/sat_curve_widget.h"
//#include "gui/widgets/sat_debug_observer_widget.h"
#include "gui/widgets/sat_drag_value_widget.h"
#include "gui/widgets/sat_dual_slider_widget.h"
//#include "gui/widgets/sat_dual_slider_widget.0.h"
#include "gui/widgets/sat_dual_value_widget.h"
#include "gui/widgets/sat_freq_resp_widget.h"
#include "gui/widgets/sat_graph_widget.h"
#include "gui/widgets/sat_grid_widget.h"
#include "gui/widgets/sat_group_box_widget.h"
#include "gui/widgets/sat_image_widget.h"
#include "gui/widgets/sat_keyboard_widget.h"
#include "gui/widgets/sat_knob_widget.h"
//#include "gui/widgets/sat_knob2_widget.h"
#include "gui/widgets/sat_logo_widget.h"
#include "gui/widgets/sat_main_menu_widget.h"
#include "gui/widgets/sat_menu_item_widget.h"
#include "gui/widgets/sat_menu_widget.h"
#include "gui/widgets/sat_movable_widget.h"
#include "gui/widgets/sat_pages_widget.h"
#include "gui/widgets/sat_panel_widget.h"
//#include "gui/widgets/sat_plugin_footer_widget.h"
//#include "gui/widgets/sat_plugin_header_widget.h"
#include "gui/widgets/sat_popup_widget.h"
#include "gui/widgets/sat_range_bar_widget.h"
#include "gui/widgets/sat_root_widget.h"
#include "gui/widgets/sat_scroll_bar_widget.h"
#include "gui/widgets/sat_scroll_box_widget.h"
#include "gui/widgets/sat_selector_widget.h"
//#include "gui/widgets/sat_shader_widget.h"
#include "gui/widgets/sat_sizer_widget.h"
#include "gui/widgets/sat_slider_bank_widget.h"
#include "gui/widgets/sat_slider_widget.h"
#include "gui/widgets/sat_symbol_widget.h"
#include "gui/widgets/sat_tabs_widget.h"
//#include "gui/widgets/sat_text_box_widget.h"
#include "gui/widgets/sat_text_edit_widget.h"
#include "gui/widgets/sat_timeline_widget.h"
#include "gui/widgets/sat_tooltip_widget.h"
#include "gui/widgets/sat_value_graph_widget.h"
//#include "gui/widgets/sat_voices_widget.h"
#include "gui/widgets/sat_waveform_widget.h"

//----------------------------------------------------------------------
#endif